ALTER TABLE Customer
ALTER COLUMN city TYPE VARCHAR(50);

ALTER TABLE Customer
ALTER COLUMN phone_number TYPE BIGINT;

UPDATE Customer
SET city = 'Milwaukee'
WHERE customer_id = 1;

ALTER TABLE staff
ALTER COLUMN phone_number TYPE BIGINT;

UPDATE Staff
SET phone_number = 9876543211
WHERE staff_id = 2;

UPDATE Movie_Time
SET date = '2023-04-15', time_screening = '16:30'
WHERE movie_time_id = 1;

UPDATE Movie_Time
SET date = '2023-04-16', time_screening = '21:00'
WHERE movie_time_id = 3;

DELETE FROM Seats
WHERE seat_id = 5;

UPDATE Ticket
SET price = 13.50
WHERE ticket_id = 3;

SELECT staff_id, first_name, last_name, phone_number FROM Staff;


--Retrieve ticket details along with the corresponding customer, staff, and seat details
SELECT t.*, c.first_name AS customer_first_name, c.last_name AS customer_last_name,
s.first_name AS staff_first_name, s.last_name AS staff_last_name,
st."row", st.hall_id
FROM Ticket t
JOIN Customer c ON t.customer_id = c.customer_id
JOIN Staff s ON t.staff_id = s.staff_id
JOIN Seats st ON t.seat_id = st.seat_id;


--Retrieve customer details along with the corresponding staff details for the tickets they have purchased:
SELECT c.*, s.first_name AS staff_first_name, s.last_name AS staff_last_name
FROM Customer c
JOIN Ticket t ON c.customer_id = t.customer_id
JOIN Staff s ON t.staff_id = s.staff_id;


--Retrieve the customer details for tickets that were purchased for movies with a specific genre

SELECT c.*
FROM Customer c
WHERE customer_id IN (
    SELECT customer_id FROM Ticket
    WHERE movie_time_id IN (
        SELECT movie_time_id FROM Movie_Time
        WHERE movie_id IN (
            SELECT movie_id FROM Movie
            WHERE movie_genre = 'Action'
        )
    )
);

--Retrieve the movies that have the highest rating

SELECT *
FROM Movie
WHERE movie_rating = 
(
	SELECT MAX(movie_rating) 
	FROM Movie
);

-- Retrieve the total revenue generated by each movie

SELECT m.movie_name, SUM(t.price) AS total_revenue
FROM Movie m
JOIN Movie_Time mt ON m.movie_id = mt.movie_id
JOIN Ticket t ON mt.movie_time_id = t.movie_time_id
GROUP BY m.movie_name;